### ISSUE TITLE
穿透获取非数据库对象

### ISSUE THREAD

**Issue by wm26hua** [dromara/easy-query#216]
穿透获取非数据库对象，这样就能多级嵌套穿透。（奢求下能配合插件使用，多层级的数据结构，手动构造太痛苦了）

**Comment by wm26hua** [comment]
![image](https://github.com/xuejmnet/easy-query/assets/30584829/c7b89e36-1384-41cf-a67c-991e2b83c137)
想了下，插件的终极形态，应该是两颗树

**Comment by xuejmnet** [comment]
<img width="1093" alt="48f74e1367a11c4ae604b6eb0f3f7720" src="https://github.com/dromara/easy-query/assets/18061232/eca753e5-c7c8-412a-97b2-a461859c5d6d">
建议升级到2.0.25 插件升级到0.0.60(没插件就不需要升级)

**Comment by xuejmnet** [comment]
光标移动到属性上面,右键generate就是呼出get set的方法,插件有个NavigateGenerate会生成
