### ISSUE TITLE
ProxyEntityAvailable 接口继承问题

### ISSUE THREAD

**Issue by lzl1030152809** [dromara/easy-query#220]
父类实现 ProxyEntityAvailable 接口，子类不继承时会报错 is not implements ProxyEntityAvailable
<img width="977" alt="image" src="https://github.com/dromara/easy-query/assets/20924956/6cfcf252-3cff-4f9a-9ba5-1b42a15d4069">
只找了子类实现的接口，未找父类实现的接口

**Comment by xuejmnet** [comment]
@lzl1030152809 您好请问是否可以发一下您现在的代码，因为正常情况下这个接口是无法做到继承的除非父类也确定具体类型才可以

**Comment by lzl1030152809** [comment]
public abstract class BaseModel<TEntity, TProxy extends ProxyEntity<TProxy, TEntity>> implements ProxyEntityAvailable<TEntity, TProxy> {
}
@xuejmnet

**Comment by xuejmnet** [comment]
@lzl1030152809 您先在子类手动实现一下我下个版本修复：）

**Comment by lzl1030152809** [comment]
@xuejmnet 好的

**Comment by xuejmnet** [comment]
@lzl1030152809 主要这个接口实现可以通过插件快速实现所以没考虑到这个情况

**Comment by lzl1030152809** [comment]
@xuejmnet 好的
