### ISSUE TITLE
希望添加一个主键生成接口标准，让用户自主实现接口来返回主键Id

### ISSUE THREAD

**Issue by chengliang4810** [dromara/easy-query#231]
我看到官网案例中的案例是，在Base实体类中设置主键字段，在实体拦截器中转换为Base实体类进行设置值。那么当不继承Base类的情况，就没办法给对象的主键设置主键Id。

**Comment by xuejmnet** [comment]
@chengliang4810 可以通过以下方式来实现
```java
public interface HasId{
     String getId();
     void setId(String id);
}

@Data
public class MyUser implements HasId{
      private String id;
}

```
拦截器判断
```
 @Override
    public boolean apply(Class<?> entityClass) {
        return HasId.class.isAssignableFrom(entityClass);
    }
```
当然这只是一种手段你也可以使用注解模式
```java
@Data
@HasIdAnnotation
public class MyUser{
      private String id;
}


    @Override
    public void configureInsert(Class<?> entityClass, EntityInsertExpressionBuilder entityInsertExpressionBuilder, Object entity) {
        EntityMetadata entityMetadata = entityInsertExpressionBuilder.getRuntimeContext().getEntityMetadataManager().getEntityMetadata(entityClass);
        ColumnMetadata columnOrNull = entityMetadata.getColumnOrNull("id");
        if(columnOrNull!=null){
            columnOrNull.getSetterCaller().call(entity,"我的id");
        }
        //apply处判断是否有注解HasIdAnnotation
    }
```

**Comment by xuejmnet** [comment]
我只是给出了一种模式您如果想要其他的可以自行实现毕竟我也不知道你要什么id或者说id本来就是跟着业务走的而不是框架提供的如果我提供了雪花id那么可能使用雪花id的人很方便但是如果您使用变种的雪花id那么我是否又要增加一个呢

**Comment by chengliang4810** [comment]
> 我只是给出了一种模式您如果想要其他的可以自行实现毕竟我也不知道你要什么id或者说id本来就是跟着业务走的而不是框架提供的如果我提供了雪花id那么可能使用雪花id的人很方便但是如果您使用变种的雪花id那么我是否又要增加一个呢

如果由您来实现每一种生成方式肯定不合适，比较理想的方案应该是您来定个标准接口即可，例如下方代码
`
public interface PrimaryKeyGenerator {

        Serializable getPrimaryKey();
        
    }
`

您的程序中只需要调用该接口的实例来获取结果即可，当然在这个标准接口下您可以增加一些常用的Id生成策略，比如雪花ID、UUId之类的。

**Comment by xuejmnet** [comment]
非常棒的一个想法

**Comment by xuejmnet** [comment]
<img width="833" alt="image" src="https://github.com/dromara/easy-query/assets/18061232/a1a91032-9dd6-45e2-a9a8-517fb4566857">
<img width="744" alt="image" src="https://github.com/dromara/easy-query/assets/18061232/16181ec5-2990-48b4-87be-0cca99028a17">

<img width="1017" alt="image" src="https://github.com/dromara/easy-query/assets/18061232/6d098b65-7ed7-4907-a439-efa1311d78f2">

赋值会在interceptor之前进行,如果有不需要赋值的可以自行在拦截器里面取消掉 版本2.0.36+

**Comment by xuejmnet** [comment]
@chengliang4810 
http://www.easy-query.com/easy-query-doc/guide/adv/auto-key.html
