### ISSUE TITLE
字段映射错误 xxxEntity not found property:[xxx] mapping column name

### ISSUE THREAD

**Issue by zhaxg** [dromara/easy-query#257]
@Column(value = "C_USER_NAME")
    private String cUserName;

这个映射会报错：xxxEntity not found property:[xxx] mapping column name
但是我把propertyName改为 userName，那么就是正常的
根据设计，只要@Column(value = "C_USER_NAME")强制映射了，propertyName叫什么都应该是一致的结果
我猜可能是字段的前缀 C_ 导致出现的故障

我还用 entityMetadataManager 对象检查了映射信息，实际上里面是正确的！只是在使用查询的时候出错了。。。

**Comment by xuejmnet** [comment]
<img width="961" alt="image" src="https://github.com/user-attachments/assets/4631640a-4f8d-4361-932b-a011ce50e93a">

<img width="1564" alt="image" src="https://github.com/user-attachments/assets/c62e5061-623d-407d-857e-34099cca30c3">


<img width="1329" alt="image" src="https://github.com/user-attachments/assets/aa39955e-7e9d-40e6-bfec-22f51100af2c">


框架在使用的时候会告知有这个问题,就是property不应该这么写,你可以用private String uerName而不是cUserName这是java的bean规范导致的两者不一致

**Comment by xuejmnet** [comment]
property是框架后续需要对get set进行调用和赋值的但是cUserName这种不符合规范的会出现奇奇怪怪的问题

**Comment by xuejmnet** [comment]
<img width="792" alt="image" src="https://github.com/user-attachments/assets/b7a64525-5111-4d70-8122-9c62aeaf2d41">
<img width="963" alt="image" src="https://github.com/user-attachments/assets/f026b018-0170-4992-83d4-073940c8d312">

**Comment by zhaxg** [comment]
明白了，确实是c#转过来的表设计和代码，谢谢！
