### ISSUE TITLE
期望支持 无中间表的 "数据多对多查询(非严格意义)"

### ISSUE THREAD

**Issue by link2fun** [dromara/easy-query#259]
销售范围上 有 客户ID, 
订单上   也有  客户ID
理论上应该可以直接通过 订单上的 客户ID 关联 销售范围的 客户ID
就直接能把销售范围的数据查出来, 没有必要多查询 客户表

目前能实现的是 
订单上 挂载 客户(多对一), 客户上挂载 销售范围(一对多)

期望实现
订单上可以直接挂载销售范围(可能不算是严格意义上的多对多, 算是无中间表的实际上的多多关系)

**Comment by xuejmnet** [comment]
@link2fun 您可以试试一对多，双向都是一对多，应该算是非主键的关系键

**Comment by link2fun** [comment]
确认可以
