### ISSUE TITLE
limit 和 firstOrNull 的逻辑似乎有点矛盾

### ISSUE THREAD

**Issue by swiftlei** [dromara/easy-query#260]
当执行下面的语句

.where(...)
.....
.orderBy(...)
.limit(100, 1)
.firstOrNull()

时，返回的结果总是符合查询条件的第一条记录，而不是 limit 指定的 offset 100后的第一条

如果修改为 
...
limit(100,1)
.toList().get(0)

则获得的是正确的offset 100条以后的第一条记录.

请问一下这样的情况是bug, 还是设计的逻辑本就如此？

**Comment by xuejmnet** [comment]
@swiftlei 我猜你想要的是singleOrNull

**Comment by xuejmnet** [comment]
singlexxx会返回并且断言至多一条

**Comment by xuejmnet** [comment]
limit的操作是覆盖之前的limit，firsXXX自带limit(1)

**Comment by xuejmnet** [comment]
如果你想要firstOrNull应该这么写where.limit(100,1).select(t->t).firstOrNull()

**Comment by xuejmnet** [comment]
limit的设计之初是同层级limit多次会覆盖之前的，同层级是指在遇到下一个select之前，因为每次select相当于是一次匿名表比如select * from (select id,name from table where xxx) t

**Comment by swiftlei** [comment]
> @swiftlei 我猜你想要的是singleOrNull

谢谢，所以如果需要我要的取第101条数据的效果，应该是 limit(100,1).singleOrNull()？

**Comment by xuejmnet** [comment]
@swiftlei 是的
