### ISSUE TITLE
kotlin下findOrNull为什么会有这个参数？

### ISSUE THREAD

**Issue by MzxVegle** [dromara/easy-query#263]
![image](https://github.com/user-attachments/assets/b3967ac8-7285-40f2-a63c-8fdc3d75d322)

**Comment by MzxVegle** [comment]
大佬，好像官网的例子里都没有看到有这个api的说明。不太懂这个里面要给个什么参数？貌似给啥返回的都是一个null

**Comment by xuejmnet** [comment]
firstOrNull是根据条件返回第一个或者null

findOrNull是根据id返回或者null

singleOrNull是根据条件返回至多一个或者null，当返回多个报错

所以findOrNull是让你穿入id的快速查询

**Comment by MzxVegle** [comment]
> firstOrNull是根据条件返回第一个或者null
> 
> findOrNull是根据id返回或者null
> 
> singleOrNull是根据条件返回至多一个或者null，当返回多个报错
> 
> 所以findOrNull是让你穿入id的快速查询

感谢大佬，回复的真快~看了一下源码才知道得传个id，一时没有反应过来。另外，findOrNull这个参数是做了混淆还是啥吗？其他的变量名都是id，这个就偏偏变成了var1，这样似乎有点儿不明显，有点强迫症哈哈哈，不过问题不大。框架做的不错，多少找回了点php的那些orm的感觉了

**Comment by xuejmnet** [comment]
你看下是不是idea没有下载源码，如果没有那么idea反编译默认var 1-n

**Comment by MzxVegle** [comment]
> 你看下是不是idea没有下载源码，如果没有那么idea反编译默认var 1-n

目前有支持ksp么？在mavenCentral上看到有sql-ksp-processor但貌似好像啥也没引进去欸？

**Comment by xuejmnet** [comment]
@MzxVegle 2.0.71最新发布加上了之前版本有问题没有吧源码加进去

**Comment by xuejmnet** [comment]
当然你也可以自己扣出来源码有maven版本和gradle版本的 可以加群是群友提供的ksp的处理
