### ISSUE TITLE
clickhouse解析Date类型好像没有带''

### ISSUE THREAD

**Issue by lemon3853** [dromara/easy-query#268]
查询方法如下：q.enterTime().rangeOpen(beginDate, endDate);
生成sql如下：WHERE (`enter_time` >= 2024-10-06 00:00:00 AND `enter_time` <= 2024-10-07 00:00:00)
报错
```
java.sql.BatchUpdateException: Code: 62. DB::Exception: Syntax error: failed at position 533 ('00'): 00:00:00 AND `enter_time` <= 2024-10-07 00:00:00). Expected one of: token, DoubleColon, Comma, ClosingRoundBracket, OR, AND, IS NOT DISTINCT FROM, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, alias, AS. (SYNTAX_ERROR) (version 24.3.2.23 (official build))
```

**Comment by xuejmnet** [comment]
@lemon3853 什么版本

**Comment by lemon3853** [comment]
> @lemon3853 什么版本

2.0.82

**Comment by xuejmnet** [comment]
@lemon3853 先升到最新试试2.0.91

**Comment by xuejmnet** [comment]
eq的所有操作是prepareStatment所以不应该有要不要加双引号这个问题,建议发截图我看看是什么问题

**Comment by xuejmnet** [comment]
除非是clickhouse的驱动不支持Date类型

**Comment by lemon3853** [comment]
> 或者试试LocalDateTime？你可以先升级到最新的eq然后看看还有没有这个错误之前和filterConfigure在一起会有一个bug新版本已经修复了

已测试，LocalDateTime没有这个问题

**Comment by xuejmnet** [comment]
> > 或者试试LocalDateTime？你可以先升级到最新的eq然后看看还有没有这个错误之前和filterConfigure在一起会有一个bug新版本已经修复了
> 
> 
> 
> 已测试，LocalDateTime没有这个问题

这种情况应该是驱动或eq对date的处理让clickhouse报错了可以尝试讲DateTypeHandler进行手动替换掉试试

**Comment by lemon3853** [comment]
> > > 或者试试LocalDateTime？你可以先升级到最新的eq然后看看还有没有这个错误之前和filterConfigure在一起会有一个bug新版本已经修复了
> > 
> > 
> > 已测试，LocalDateTime没有这个问题
> 
> 这种情况应该是驱动或eq对date的处理让clickhouse报错了可以尝试讲DateTypeHandler进行手动替换掉试试，当然eq的版本建议升到最新

升级到最新版了，改用LocalDateTime
