### ISSUE TITLE
请问clickhouse怎么加final关键字

### ISSUE THREAD

**Issue by lemon3853** [dromara/easy-query#269]
```
select * from users final
```

**Comment by xuejmnet** [comment]
@lemon3853 
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/c3ec72c3-ddde-4c3b-83d1-e32d96e3db58">
下个版本支持

**Comment by xuejmnet** [comment]
@lemon3853 2.0.95已发布

**Comment by lemon3853** [comment]
> @lemon3853 2.0.95已发布

芜湖！
