### ISSUE TITLE
实体类加了@Column注解，但是没有映射成功

### ISSUE THREAD

**Issue by lemon3853** [dromara/easy-query#270]
![图片](https://github.com/user-attachments/assets/01d02b71-1ae8-43dc-b34e-868226e00717)
注解如下
@Column(value = "r_mdid")
private Integer rMdid;
查询期间出现日志
c.e.query.core.metadata.EntityMetadata  238              : Mddbd filed:rMdid,compare name:rMdid,property name:RMdid

**Comment by xuejmnet** [comment]
建议将属性名修改为正规的可映射的bean属性,不然很容易出现各种bug,建议将rMidid改成midid或者其他字段

**Comment by xuejmnet** [comment]
比如boolean类型不可以用is开头一样这些都是java的bean规范 ： ）

**Comment by xuejmnet** [comment]
@lemon3853 您应该是其他语言转过来的吧这个哪怕eq支持了后续可能其他序列化框架也会出现问题建议还是属性名不要使用这种

**Comment by lemon3853** [comment]
> 建议将属性名修改为正规的可映射的bean属性,不然很容易出现各种bug,建议将rMidid改成midid或者其他字段

数据库字段就是r_mdid，已经将实体类字段名称改成r_mdid了，可以解决问题

**Comment by lemon3853** [comment]
> 建议将属性名修改为正规的可映射的bean属性,不然很容易出现各种bug,建议将rMidid改成midid或者其他字段

用eq的idea插件生成的代码，下次取消驼峰转化.
