### ISSUE TITLE
排序问题

### ISSUE THREAD

**Issue by mcode999** [dromara/easy-query#272]
怎么实现mysql数据库的order by field(字段名,"字段值1","字段值2",...)这种排序呢

**Comment by xuejmnet** [comment]
@mcode999 通过使用sql片段即可

http://www.easy-query.com/easy-query-doc/query/native-sql.html#%E9%9A%8F%E6%9C%BA%E6%8E%92%E5%BA%8F%E5%B8%A6%E5%8F%82%E6%95%B0

```java
 List<SysUserEntity> list = easyEntityQuery.queryable(SysUserEntity.class)
                .orderBy(user -> {
                    user.expression().sql("FIELD({0},{1},{2})", c -> {
                        c.expression(user.id()).expression(user.userName()).expression(user.phone());
                    });
                }).toList();
```

<img width="2012" alt="image" src="https://github.com/user-attachments/assets/c0ac398d-4aca-445d-8852-f38ff6927566">
