### ISSUE TITLE
[建议] 建议 idea 插件支持检测字段命名是否符合规范, 以避免编码阶段不报错, 运行阶段因为字段名不对应导致报错

### ISSUE THREAD

**Issue by link2fun** [dromara/easy-query#274]
![image](https://github.com/user-attachments/assets/b9abdabd-9ccc-420e-9c56-ad59430eddae)

![image](https://github.com/user-attachments/assets/64b1c107-e2e9-441c-81a4-3259b86018cf)

**Comment by xuejmnet** [comment]
@link2fun 2.0.102版本支持eq的entity模式指定使用field作为属性而不是默认的首字母小写

http://www.easy-query.com/easy-query-doc/config/config-option.html#%E9%BB%98%E8%AE%A4%E9%85%8D%E7%BD%AE%E9%A1%B9

<img width="1856" alt="image" src="https://github.com/user-attachments/assets/b78ae3cf-d0cd-4e2e-a47b-897bfd88e58e">

如果您是自行构建的eq实例那么可以选择替换服务
```java
  easyQueryClient = EasyQueryBootstrapper.defaultBuilderConfiguration()
                .setDefaultDataSource(dataSource)
                .optionConfigure(op -> {
                    op.setDeleteThrowError(false);
                })
                .useDatabaseConfigure(new MySQLDatabaseConfiguration())
                //替换服务
                .replaceService(PropertyDescriptorMatcher.class, EntityPropertyDescriptorMatcher.class)
                .build();
```
