### ISSUE TITLE
entity模式如何使用数据库函数

### ISSUE THREAD

**Issue by Gn3po4g** [dromara/easy-query#276]
```sql
SELECT name, IF(salary > 5000, '高级', '普通') as rank,  0 status FROM employees;
```
比如上面的语句，如何在easyEntityQuery中实现对if函数和常量的查询？目前的方式是查询成VO后手动赋值

**Comment by Gn3po4g** [comment]
似乎可以通过`expression().sqlSegment`实现

**Comment by xuejmnet** [comment]
@Gn3po4g 返回结果可以通过expression.sqlSegement但是这边建议使用更通用的函数`expression().caseWhen().then().caseWhen().then().elseEnd().asAnyType(String.class)`
毕竟`if(condition,trueValue,elseValue)`并不是通用函数

**Comment by Gn3po4g** [comment]
感谢解惑！感觉好多功能文档里都没介绍到

**Comment by xuejmnet** [comment]
@Gn3po4g 谢谢提醒我最近在整理文档了估计1-2星期会有一份新文档出来
